[package]
name = "bootmanager_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.22.4"
thiserror = "2.0.20"
log = "0.4.34"
rsbinder = "0.10"
rustix = {
    version = "1.1",
    features = ["fs"]
}

[build-dependencies]
rsbinder-aidl = "0.10"

[features]
aidl = []
hidl = []
legacy-ffi = []
