[package]
name = "bootmanager_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.22.4"
thiserror = "2.0.20"
log = "0.4.34"
async-trait = "0.1.*"
rustix = {
    version = "1.1",
    features = ["fs"]
}
rsbinder = {
    version = "0.10",
    features = ["async"]
}

[build-dependencies]
rsbinder-aidl = {
    version = "0.10",
    features = ["async"]
}

[features]
aidl = []
hidl = []
legacy-ffi = []
